name: Y4K13 No-PIL Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install "yt-dlp[default,curl-cffi]" customtkinter pyinstaller

    - name: Build Single EXE
      # We removed --collect-all PIL entirely
      run: pyinstaller --noconfirm --onefile --windowed --add-data "miku_peak.png;." --collect-all customtkinter --name "Y4K13_Downloader" app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Y4K13-Application
        path: dist/Y4K13_Downloader.exe